### ISSUE TITLE
Needed to download org.json.jar on OSX

### ISSUE THREAD

**Issue by gitonthescene** [ryanfb/georefine#1]
Hello,

I see the last edit was quite a while ago, but I thought I'd post anyway.  I tried installing this extension, but got the following error:

``` sh
$ /Applications/OpenRefine.app/Contents/MacOS/JavaAppLauncher
10:29:28.537 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
10:29:28.551 [            refine_server] Initializing context: '/' from '/Applications/OpenRefine.app/Contents/Resources/webapp' (14ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Java/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Applications/OpenRefine.app/Contents/Resources/webapp/WEB-INF/lib/slf4j-log4j12-1.7.18.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
10:29:29.085 [                   refine] Starting OpenRefine 3.4.1 [437dc4d]... (534ms)
10:29:29.085 [                   refine] initializing FileProjectManager with dir (0ms)
10:29:29.085 [                   refine] /Users/douglasmennella/Library/Application Support/OpenRefine (0ms)
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONWriter
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetPublicMethods(Class.java:2902)
        at java.lang.Class.getMethods(Class.java:1615)
...
```

The error only came when installing this extension.  I installed the extension in the [workspace directory](https://docs.openrefine.org/manual/installing/#installing-extensions).  I'm running OpenRefine 3.4.1 on OSX Big Sur.

Downloading [org.json](https://mvnrepository.com/artifact/org.json/json/20140107) and installing it under `extensions/georefine-master/module/MOD-INF/lib/` makes it all work.

I don't know if you want/need to update the install instructions, but hopefully this issue will help someone else.

Regards,

**Comment by ryanfb** [comment]
Thanks, I haven't taken a look at this extension in a while. It seems like what probably happened is that OpenRefine no longer bundles this JAR and uses something else instead now. I'll add it to the distribution so that there shouldn't be any additional install steps necessary.
